### ISSUE TITLE
Skype messages cannot be updated immediately

### ISSUE THREAD

**Issue by rused** [BlackCapCoder/pskype#1]
When you update a message inline (by hitting the arrow up key, or "edit message") the message does not update in the actual window. You can see the small pen that notes that the message has been edited, but you cannot see the modification.

**Comment by BlackCapCoder** [comment]
This was fixed earlier today
https://github.com/BlackCapCoder/pskype/commit/5bb931662e2157dc76fd2db02187c0ec868e3c12
